### ISSUE TITLE
[Feature Request] System Tray

### ISSUE THREAD

**Issue by xii69** [sejjy/mechabar#8]
Hey, just found your amazing Waybar configuration on Waybar's wiki examples, but this needs a system tray too, could you add one please?

**Comment by sejjy** [comment]
Hi,

When you say **"system tray"**, do you mean icons for programs running in the background? If yes, I did not include those because, if I'm not mistaken, Waybar cannot change the appearance of the icons. My concern is that the bar might look inconsistent since the icons could have different colors, shapes, and sizes that may not align well with a themed bar.

However, if you want to display those icons, you can replace an existing module with the contents of **[taskbar.jsonc](https://github.com/sejjy/mechabar/blob/main/modules/taskbar.jsonc)** from the **modules** folder.

Let me know if you have any more questions. :)

Warm regards,  
Jesse

**Comment by xii69** [comment]
ow didn't saw, thanks a lot
